Enabled i18n. Removed sync.
Enabled internationalization. Removed unnecessary sync to let the kernel decide when to flush (e.g. during unmount). Updated messages to be clearer. Made do_memory_split more generic and i18n friendly.

diff --git a/raspi-config b/raspi-config
--- a/raspi-config
+++ b/raspi-config
@@ -5,14 +5,14 @@
 
 
 if [ $(id -u) -ne 0 ]; then
-  printf "Script must be run as root. Try 'sudo raspi-config'\n"
+  printf $"Script must be run as root. Try 'sudo raspi-config'\n"
   exit 1
 fi
 
 ASK_TO_REBOOT=0
 
 do_info() {
-  whiptail --msgbox "\
+  whiptail --msgbox $"\
 This tool provides a straight-forward way of doing initial 
 configuration of the Raspberry Pi. Although it can be run 
 at any time, some of the options may have difficulties if 
@@ -57,21 +57,21 @@ cat <<\EOF > /etc/init.d/resize2fs_once &&
 
 case "$1" in
   start)
-    log_daemon_msg "Starting resize2fs_once" &&
+    log_daemon_msg $"Starting" resize2fs_once &&
     resize2fs /dev/mmcblk0p2 &&
     rm /etc/init.d/resize2fs_once &&
     update-rc.d resize2fs_once remove &&
     log_end_msg $?
     ;;
   *)
-    echo "Usage: $0 start" >&2
+    echo $"Usage:" "$0 start" >&2
     exit 3
     ;;
 esac
 EOF
   chmod +x /etc/init.d/resize2fs_once &&
   update-rc.d resize2fs_once defaults &&
-  whiptail --msgbox "Root partition has been resized.\n\
+  whiptail --msgbox $"Root partition has been resized.\n\
 The filesystem will be enlarged upon the next reboot" 20 60 2
 }
 
@@ -115,7 +115,7 @@ set_overscan() {
 }
 
 do_overscan() {
-  whiptail --yesno "What would you like to do with overscan" 20 60 2 \
+  whiptail --yesno $"What would you like to do with overscan" 20 60 2 \
     --yes-button Disable --no-button Enable 
   RET=$?
   if [ $RET -eq 0 ] || [ $RET -eq 1 ]; then
@@ -127,14 +127,14 @@ do_overscan() {
 }
 
 do_change_pass() {
-  whiptail --msgbox "You will now be asked to enter a new password for the pi user" 20 60 1
+  whiptail --msgbox $"You will now be asked to enter a new password for the pi user" 20 60 1
   passwd pi &&
-  whiptail --msgbox "Password changed successfully" 20 60 1
+  whiptail --msgbox $"Password changed successfully" 20 60 1
 }
 
 do_configure_keyboard() {
   dpkg-reconfigure keyboard-configuration &&
-  printf "Reloading keymap. This may take a short while\n" &&
+  printf $"Reloading keymap. This may take a short while\n" &&
   invoke-rc.d keyboard-setup start
 }
 
@@ -151,51 +151,47 @@ do_memory_split() {
   if ! mountpoint -q /boot; then
     return 1
   fi
-  local CURRENT_MEMSPLIT AVAILABLE_SPLITS
-  AVAILABLE_SPLITS="128 192 224 240"
-  CURRENT_MEMSPLIT=$(
-    for SPLIT in $AVAILABLE_SPLITS;do
-      if cmp /boot/arm${SPLIT}_start.elf /boot/start.elf >/dev/null 2>&1;then
-        echo $SPLIT
-        exit 0
-      fi
-    done
-    )
-    MEMSPLIT=$(whiptail --menu "Set memory split.\nCurrent: ${CURRENT_MEMSPLIT}MiB for ARM, $((256 - $CURRENT_MEMSPLIT))MiB for VideoCore" 20 60 10 \
-    "240" "240MiB for ARM, 16MiB for VideoCore" \
-    "224" "224MiB for ARM, 32MiB for VideoCore" \
-    "192" "192MiB for ARM, 64MiB for VideoCore" \
-    "128" "128MiB for ARM, 128MiB for VideoCore" \
-    3>&1 1>&2 2>&3)
+  AVAILABLE_SPLITS="240 224 192 128"
+  MEMSPLIT_LIST=()
+  MEMSPLIT_DESCRIPTION=""
+  for SPLIT in $AVAILABLE_SPLITS;do
+    if [ -z "$MEMSPLIT_DESCRIPTION" ] && cmp /boot/arm${SPLIT}_start.elf /boot/start.elf >/dev/null 2>&1;then
+      CURRENT_MEMSPLIT=$SPLIT
+      MEMSPLIT_DESCRIPTION=$( printf $"Current: %sMiB for ARM, %sMiB for VideoCore" ${CURRENT_MEMSPLIT} $((256 - $CURRENT_MEMSPLIT)) )
+    fi
+    MEMSPLIT_LIST=( "${MEMSPLIT_LIST[@]}" $SPLIT )
+    MEMSPLIT_LIST_DESCRIPTION=$SPLIT$"MiB for ARM, "$SPLIT$"MiB for VideoCore"
+    MEMSPLIT_LIST=( "${MEMSPLIT_LIST[@]}" "$MEMSPLIT_LIST_DESCRIPTION" )
+  done
+  MEMSPLIT=$(whiptail --menu $"Set memory split.""\n$MEMSPLIT_DESCRIPTION" 20 60 10 "${MEMSPLIT_LIST[@]}" 3>&1 1>&2 2>&3)
   if [ $? -eq 0 ]; then
     cp -a /boot/arm${MEMSPLIT}_start.elf /boot/start.elf
-    sync
     ASK_TO_REBOOT=1
   fi
 }
 
 do_ssh() {
   if [ -e /var/log/regen_ssh_keys.log ] && ! grep -q "^finished" /var/log/regen_ssh_keys.log; then
-    whiptail --msgbox "Initial ssh key generation still running. Please wait and try again." 20 60 2
+    whiptail --msgbox $"Initial ssh key generation still running. Please wait and try again." 20 60 2
     return 1
   fi
-  whiptail --yesno "Would you like the SSH server enabled or disabled?" 20 60 2 \
-    --yes-button Enable --no-button Disable 
+  whiptail --yesno $"Would you like the SSH server enabled or disabled?" 20 60 2 \
+    --yes-button $"Enable" --no-button $"Disable"
   RET=$?
   if [ $RET -eq 0 ]; then
     update-rc.d ssh enable &&
     invoke-rc.d ssh start &&
-    whiptail --msgbox "SSH server enabled" 20 60 1
+    whiptail --msgbox $"SSH server enabled" 20 60 1
   elif [ $RET -eq 1 ]; then
     update-rc.d ssh disable &&
-    whiptail --msgbox "SSH server disabled" 20 60 1
+    whiptail --msgbox $"SSH server disabled" 20 60 1
   else
     return $RET
   fi
 }
 
 do_boot_behaviour() {
-  whiptail --yesno "Should we boot straight to desktop?" 20 60 2
+  whiptail --yesno $"Should we boot straight to desktop?" 20 60 2
   RET=$?
   if [ $RET -eq 0 ]; then # yes
     update-rc.d lightdm enable 2
@@ -212,7 +208,7 @@ do_boot_behaviour() {
 do_update() {
   apt-get update &&
   apt-get install raspi-config &&
-  printf "To start raspi-config again, do 'sudo raspi-config'. Now exiting\n"
+  printf $"To start raspi-config again, run 'sudo raspi-config'\n"
   exit 0
 }
 
@@ -225,9 +221,8 @@ do_finish() {
     telinit q
   fi
   if [ $ASK_TO_REBOOT -eq 1 ]; then
-    whiptail --yesno "Would you like to reboot now?" 20 60 2
+    whiptail --yesno $"Would you like to reboot now?" 20 60 2
     if [ $? -eq 0 ]; then # yes
-      sync
       reboot
     fi
   fi
@@ -236,23 +231,23 @@ do_finish() {
 
 while true; do
   FUN=$(whiptail --menu "Raspi-config" 20 80 12 --cancel-button Finish --ok-button Select \
-    "info" "Information about this tool" \
-    "expand_rootfs" "Expand root partition to fill SD card" \
-    "overscan" "Change overscan" \
-    "configure_keyboard" "Set keyboard layout" \
-    "change_pass" "Change password for 'pi' user" \
-    "change_locale" "Set locale" \
-    "change_timezone" "Set timezone" \
-    "memory_split" "Change memory split" \
-    "ssh" "Enable or disable ssh server" \
-    "boot_behaviour" "Start desktop on boot?" \
-    "update" "Try to upgrade raspi-config" \
+    "info" $"Information about this tool" \
+    "expand_rootfs" $"Expand root partition to fill SD card" \
+    "overscan" $"Change display overscan" \
+    "configure_keyboard" $"Set keyboard layout" \
+    "change_pass" $"Change password for 'pi' user" \
+    "change_locale" $"Set locale" \
+    "change_timezone" $"Set timezone" \
+    "memory_split" $"Change memory split" \
+    "ssh" $"Enable or disable ssh server" \
+    "boot_behaviour" $"Start desktop on boot?" \
+    "update" $"Try to upgrade raspi-config" \
     3>&1 1>&2 2>&3)
   RET=$?
   if [ $RET -eq 1 ]; then
     do_finish
   elif [ $RET -eq 0 ]; then
-    "do_$FUN" || whiptail --msgbox "There was an error running do_$FUN" 20 60 1
+    "do_$FUN" || whiptail --msgbox "$(printf "There was an error running %s function." do_$FUN)" 20 60 1
   else
     exit 1
   fi
